// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rentify.DataAccess.Data;

#nullable disable

namespace Rentify.DataAccess.Migrations
{
    [DbContext(typeof(RentifyDbContext))]
    partial class RentifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rentify.Core.Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("money");

                    b.Property<decimal>("AmountPayable")
                        .HasColumnType("money");

                    b.Property<DateTime>("BillEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("BillStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BillType")
                        .HasColumnType("int");

                    b.Property<int>("BillVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantContractAllocationId")
                        .HasColumnType("int");

                    b.HasKey("BillId");

                    b.HasIndex("TenantContractAllocationId");

                    b.HasIndex("BillNumber", "BillVersion")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Rentify.Core.Entities.BillLineItem", b =>
                {
                    b.Property<int>("BillLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillLineItemId"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("BillItemType")
                        .HasColumnType("int");

                    b.Property<decimal>("LineItemAmount")
                        .HasColumnType("money");

                    b.Property<string>("LineItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LineItemOrder")
                        .HasColumnType("int");

                    b.Property<int?>("UtilityBillId")
                        .HasColumnType("int");

                    b.HasKey("BillLineItemId");

                    b.HasIndex("BillId");

                    b.HasIndex("UtilityBillId");

                    b.ToTable("BillLineItems");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentSettlementDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UtilityBillingMode")
                        .HasColumnType("int");

                    b.Property<int?>("UtilitySettlementDay")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex("ContractNo", "ContractVersion")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Rentify.Core.Entities.ContractRentBreakDown", b =>
                {
                    b.Property<int>("ContractRentBreakDownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractRentBreakDownId"));

                    b.Property<decimal?>("RentItemAmount")
                        .HasColumnType("money");

                    b.Property<int>("RentItemLineOrder")
                        .HasColumnType("int");

                    b.Property<string>("RentItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RentItemPercentage")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("RentItemType")
                        .HasColumnType("int");

                    b.Property<int>("TenantContractAllocationId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilityId")
                        .HasColumnType("int");

                    b.HasKey("ContractRentBreakDownId");

                    b.HasIndex("TenantContractAllocationId");

                    b.HasIndex("UtilityId");

                    b.ToTable("ContractRentBreakDowns");
                });

            modelBuilder.Entity("Rentify.Core.Entities.ContractUnitAllocation", b =>
                {
                    b.Property<int>("ContractUnitAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractUnitAllocationId"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ContractUnitAllocationId");

                    b.HasIndex("ContractId");

                    b.HasIndex("UnitId");

                    b.ToTable("ContractUnitAllocations");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Deposit", b =>
                {
                    b.Property<int>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepositId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<string>("DepositName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("money");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantContractAllocationId")
                        .HasColumnType("int");

                    b.HasKey("DepositId");

                    b.HasIndex("TenantContractAllocationId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PropertyId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Rentify.Core.Entities.TenantContractAllocation", b =>
                {
                    b.Property<int>("TenantContractAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantContractAllocationId"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("TenantContractAllocationId");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantContractAllocations");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("UnitId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Utility", b =>
                {
                    b.Property<int>("UtilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityId"));

                    b.Property<int>("BillingCycle")
                        .HasColumnType("int");

                    b.Property<DateTime>("BillingCycleStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtilityExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UtilityType")
                        .HasColumnType("int");

                    b.HasKey("UtilityId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Utilities");
                });

            modelBuilder.Entity("Rentify.Core.Entities.UtilityBill", b =>
                {
                    b.Property<int>("UtilityBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityBillId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<DateTime>("BillEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BillStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int");

                    b.HasKey("UtilityBillId");

                    b.HasIndex("UtilityId");

                    b.ToTable("UtilityBills");
                });

            modelBuilder.Entity("Rentify.Core.Entities.UtilityUnitAllocation", b =>
                {
                    b.Property<int>("UtilityUnitAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityUnitAllocationId"));

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int");

                    b.HasKey("UtilityUnitAllocationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UtilityId");

                    b.ToTable("UtilityUnitAllocations");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Bill", b =>
                {
                    b.HasOne("Rentify.Core.Entities.TenantContractAllocation", null)
                        .WithMany("Bills")
                        .HasForeignKey("TenantContractAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rentify.Core.Entities.BillLineItem", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Bill", null)
                        .WithMany("BillLineItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rentify.Core.Entities.UtilityBill", "UtilityBill")
                        .WithMany()
                        .HasForeignKey("UtilityBillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UtilityBill");
                });

            modelBuilder.Entity("Rentify.Core.Entities.ContractRentBreakDown", b =>
                {
                    b.HasOne("Rentify.Core.Entities.TenantContractAllocation", null)
                        .WithMany("ContractRentBreakDowns")
                        .HasForeignKey("TenantContractAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rentify.Core.Entities.Utility", "RentItemUtility")
                        .WithMany()
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RentItemUtility");
                });

            modelBuilder.Entity("Rentify.Core.Entities.ContractUnitAllocation", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Contract", null)
                        .WithMany("ContractUnitAllocations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Core.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Deposit", b =>
                {
                    b.HasOne("Rentify.Core.Entities.TenantContractAllocation", null)
                        .WithMany("Deposits")
                        .HasForeignKey("TenantContractAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rentify.Core.Entities.Payment", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Bill", null)
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rentify.Core.Entities.TenantContractAllocation", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Contract", null)
                        .WithMany("TenantContractAllocations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Unit", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Utility", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Rentify.Core.Entities.UtilityBill", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Utility", "Utility")
                        .WithMany()
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("Rentify.Core.Entities.UtilityUnitAllocation", b =>
                {
                    b.HasOne("Rentify.Core.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Core.Entities.Utility", null)
                        .WithMany("UtilityUnitAllocations")
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Bill", b =>
                {
                    b.Navigation("BillLineItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Contract", b =>
                {
                    b.Navigation("ContractUnitAllocations");

                    b.Navigation("TenantContractAllocations");
                });

            modelBuilder.Entity("Rentify.Core.Entities.TenantContractAllocation", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("ContractRentBreakDowns");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("Rentify.Core.Entities.Utility", b =>
                {
                    b.Navigation("UtilityUnitAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
