<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ba5a57a5-dd1b-4e3d-bb34-64adb475c17e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="NewFolder\**" />
    <Content Remove="NewFolder1\**" />
    <Content Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder1\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rentify.Application\Rentify.Application.csproj" />
    <ProjectReference Include="..\Rentify.DataAccess.SqlServer\Rentify.DataAccess.SqlServer.csproj" />
    <ProjectReference Include="..\Rentify.FileWorkflow.Implementation\Rentify.FileWorkflow.Implementation.csproj" />
    <ProjectReference Include="..\Rentify.Storage.LocalStorage\Rentify.Storage.LocalStorage.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="https://www.schemastore.org/azure-iot-edge-deployment-template-4.0.json" /></VisualStudio></ProjectExtensions>

</Project>
